title:             Relatos del camino
email:             Hakuna.Matata@gmail.com
description:       Sucesos sobre el fluir
author:            Hakuna Matata
baseurl:           "/"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          3
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
